version: '3'
services:
  bywise-node:
    container_name: bywise-node
    build: './api'
    env_file: .env
    volumes:
      - ./api:/home/node/app
    depends_on:
      - bywise-db
    networks:
      - app-connect
    ports:
      - '${PORT}:8080'

  bywise-db:
    container_name: bywise-db
    image: postgres:12.8
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - app-connect
    volumes:
      - bywise-db:/data/postgres
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '${DB_PORT}:5432'

  bywise-node2:
    container_name: bywise-node2
    build: './api'
    env_file: .env2
    volumes:
      - ./api:/home/node/app
    depends_on:
      - bywise-db
    networks:
      - app-connect
    ports:
      - '2000:8080'

volumes:
    bywise-db:

networks:
  app-connect:
    driver: bridge